export const SESSION_URL = '/openmrs/ws/rest/v1/session?v=custom:(uuid)';

export const AUTH_ERROR_KEYS = {
  INVALID_CREDENTIALS: 'LOGIN_LABEL_LOGIN_ERROR_MESSAGE_KEY',
  OTP_REQUIRED: 'LOGIN_LABEL_OTP_REQUIRED',
  OTP_EXPIRED: 'LOGIN_LABEL_OTP_EXPIRED',
  OTP_WRONG: 'LOGIN_LABEL_WRONG_OTP_MESSAGE_KEY',
  TOO_MANY_ATTEMPTS: 'LOGIN_LABEL_MAX_FAILED_ATTEMPTS',
  NETWORK: 'LOGIN_LABEL_NETWORK_ERROR',
} as const;
