export const COMMON_ERROR_MESSAGES = {
  UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  INVALID_RESPONSE: 'INVALID_RESPONSE',
};

export const ERROR_TITLES = {
  VALIDATION_ERROR: 'ERROR_VALIDATION_TITLE',
  DASHBOARD_ERROR: 'ERROR_DASHBOARD_CONFIG_TITLE',
  CONSULTATION_ERROR: 'ERROR_CONSULTATION_TITLE',
};

export const CONSULTATION_ERROR_MESSAGES = {
  INVALID_DIAGNOSIS_PARAMS: 'CONSULTATION_ERROR_INVALID_DIAGNOSIS_PARAMS',
  INVALID_ENCOUNTER_SUBJECT: 'CONSULTATION_ERROR_INVALID_ENCOUNTER_SUBJECT',
  INVALID_ENCOUNTER_REFERENCE: 'CONSULTATION_ERROR_INVALID_ENCOUNTER_REFERENCE',
  INVALID_PRACTITIONER: 'CONSULTATION_ERROR_INVALID_PRACTITIONER',
  INVALID_ALLERGY_PARAMS: 'CONSULTATION_ERROR_INVALID_ALLERGY_PARAMS',
  INVALID_CONDITION_PARAMS: 'CONSULTATION_ERROR_INVALID_CONDITION_PARAMS',
  INVALID_IMMUNIZATION_PARAMS: 'CONSULTATION_ERROR_INVALID_IMMUNIZATION_PARAMS',
};

export const PINNED_FORMS_ERROR_MESSAGES = {
  USER_NOT_FOUND: 'PINNED_FORMS_USER_NOT_FOUND',
  INVALID_DATA: 'PINNED_FORMS_INVALID_DATA',
  LOAD_FAILED: 'ERROR_LOADING_PINNED_FORMS_MESSAGE',
  SAVE_FAILED: 'ERROR_SAVING_PINNED_FORMS_MESSAGE',
};

export const PINNED_FORMS_ERROR_TITLES = {
  LOAD_ERROR: 'ERROR_LOADING_PINNED_FORMS',
  SAVE_ERROR: 'ERROR_SAVING_PINNED_FORMS',
};
