export const APPOINTMENT_STATUS = {
  SCHEDULED: 'scheduled',
  CONFIRMED: 'confirmed',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled',
  MISSED: 'missed',
  WAITLIST: 'waitlist',
  CHECKEDIN: 'checkedin',
} as const;

export const APPOINTMENT_STATUS_CLASS_MAP: Record<string, string> = {
  [APPOINTMENT_STATUS.SCHEDULED]: 'scheduledStatus',
  [APPOINTMENT_STATUS.CONFIRMED]: 'scheduledStatus',
  [APPOINTMENT_STATUS.COMPLETED]: 'completedStatus',
  [APPOINTMENT_STATUS.CANCELLED]: 'cancelledStatus',
  [APPOINTMENT_STATUS.MISSED]: 'missedStatus',
  [APPOINTMENT_STATUS.WAITLIST]: 'waitListStatus',
  [APPOINTMENT_STATUS.CHECKEDIN]: 'checkedInStatus',
};

export const APPOINTMENT_STATUS_TRANSLATION_MAP: Record<string, string> = {
  [APPOINTMENT_STATUS.SCHEDULED]: 'APPOINTMENTS_STATUS_SCHEDULED',
  [APPOINTMENT_STATUS.CONFIRMED]: 'APPOINTMENTS_STATUS_SCHEDULED',
  [APPOINTMENT_STATUS.COMPLETED]: 'APPOINTMENTS_STATUS_COMPLETED',
  [APPOINTMENT_STATUS.CANCELLED]: 'APPOINTMENTS_STATUS_CANCELLED',
  [APPOINTMENT_STATUS.MISSED]: 'APPOINTMENTS_STATUS_MISSED',
  [APPOINTMENT_STATUS.WAITLIST]: 'APPOINTMENTS_STATUS_WAITLIST',
  [APPOINTMENT_STATUS.CHECKEDIN]: 'APPOINTMENTS_STATUS_CHECKEDIN',
};
